### ISSUE TITLE
Enable the iEEG extension (BEP 010)

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/legacy-validator#510]
This is an issue to coordinate the steps we need to take before the iEEG extension can be "activated" in the bids-validator. Right now it is off by default, but can be turned on with a flag.

Was originally in https://github.com/INCF/bids-validator/pull/451 but we decided to merge that in order to make refactoring easier.

## To-do list for this PR to get merged

- [x] Agree on how to reference the coordinate systems in the main BIDS spec
- [x] Agree on nomenclature around "electrodes" vs "contacts" (e.g. for electrode shanks vs single electrodes)
- [x] Decide on a final list of file extensions to support.
  - Current extensions suggested: EDF, VHDR
  - Current extensions allowed in addition: MEF3, SET, NWB
  - In particular @jasmainak and @teonbrooks showed concerns with having EDF as a primary format we recommend people use.
- [x] Decide whether we want javascript readers to be a blocker on the specification (no)
- [x] Decide whether we want python readers to be a blocker on the specification (no)
- [x] Figure out prefixes for units
- [x] Relatively minor spot-checks in the google doc
- [x] Final pass
- [x] Merge!

## To test out this PR on your dataset:

I believe that the following will let you demo this repository on your local machine (cc @dorahermes )
1. Fork and clone the bids-validator repository:

       git clone https://github.com/bids-standard/bids-validator
2. Install the validator for local development:

       npm install -g 

   from now on when you run `bids-validator`, it should be using the code from this branch!

3. Run the BIDS validator with the BEP 010 flag, which activates the iEEG BEP extension:
   
       bids-validator --bep010 path/to/dataset

cc @dorahermes @sappelhoff @chrisfilo and @nellh as well, just FYI!

**Comment by teonbrooks** [comment]
I think I have come around to the preferred EEG options especially in light of vhdr [writing](https://gitlab.com/palday/philistine/blob/master/philistine/mne/io.py) functionality and the its [validation](https://github.com/sappelhoff/brainvision-validator) efforts.

Since EDF is such a common format, writers already exist (although a compatible [one](https://github.com/mne-tools/mne-bids/issues/41) is needed for MNE). a js validator would be its next step.

**Comment by sappelhoff** [comment]
currently, the validator only allows BrainVision and EDF, see: https://github.com/bids-standard/bids-validator/blob/cbcb0d31c5a945ef8be9e5c2b4e380b6d7a01a58/bids_validator/rules/file_level_rules.json#L179

and by the way, is it true that the BrainVision `.eeg` file is renamed to `.dat` for iEEG data? Or where does the `.dat` come from? Who does this renaming? Software by Brain Products? help would be appreciated @dorahermes @choldgraf

**Comment by choldgraf** [comment]
That's a great question - I believe somebody told me it was called "dat" but someone more familiar with the format than I should comment :-/

**Comment by dorahermes** [comment]
I don't know where it comes from, it should be .eeg (that's how the non-empty data live on my system)

**Comment by sappelhoff** [comment]
Mmh okay, I could change that in a PR if you agree.

Also, look at this:
https://github.com/bids-standard/bids-validator/blob/3876694533738f2df73de14e9745a4f5f4ba3304/validators/bids/groupFileTypes.js#L53-L67

this `ieegTest` should be renamed to `ephysTest` in my opinion ... but the main point is: What are      
```
'tdat', 
'tidx', 
'tmet', 
```
?

**Comment by choldgraf** [comment]
@sappelhoff just saw this, that's a good question...could be that it's copypasta from another test? If we don't know of any use for those filenames in the context of the ieeg spec, I think we should just remove them.

**Comment by sappelhoff** [comment]
perhaps you could fix it in https://github.com/bids-standard/bids-validator/pull/591 ? I'd appreciate that because we need it for basic iEEG functionality of MNE-BIDS, which we want to release very soon (see https://github.com/mne-tools/mne-bids/pull/118)

**Comment by choldgraf** [comment]
@sappelhoff yep I'll take care of it in that PR (gonna try to wrap it up soon)

**Comment by choldgraf** [comment]
ok the tests are nearly passing, circle is unhappy but it's unclear what the error is.


https://circleci.com/gh/bids-standard/bids-validator/1876?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I think it's erroring on `jest --coverage`...does that mean that there isn't enough coverage in the tests?

**Comment by nellh** [comment]
It runs tests and coverage at the same time. The error is above the coverage report, looks like a syntax error in ieeg.json

**Comment by teonbrooks** [comment]
just updating the thread, i think @jasmainak and I have gotten over our reservation about the `.edf`. we're pretty happy about the state the extension and the validator. good work, team! 🎉🧠
