### ISSUE TITLE
enable the eeg Extension (BEP006)

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#592]
Similar to issue bids-standard/legacy-validator#510 concerning iEEG, we can list all the remaining To Do points for enabling the EEG validator by default (i.e., without passing the `--bep006` flag).

This list is work in progress. If you find more to dos, please comment and I can update this list. 
cc: @robertoostenveld @CPernet @arnodelorme @gllmflndn @ChristophePhillips

# To Do:
- [x] Go through [_eeg.json schema](https://github.com/bids-standard/bids-validator/blob/master/validators/json/schemas/eeg.json) and bring up to date ... see bids-standard/legacy-validator#661 
    - [x] remove field `DeviceSoftwareVersion`, which has been replaced by `SoftwareVersions`
    - [x] discuss the required format for `HardwareFilters` and `SoftwareFilters` ... also: make them required?
- [x] Go through code coverage report and make sure that all EEG related features are covered by tests
- [x] Discuss whether a non-custom column `event_types` should be included in BIDS-EEG. If yes, it should be added here: `bids_validator/tsv/non_custom_columns.json`. See [BEP spec google doc](https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE/edit#heading=h.9rets2uzyf3s) comment for why it might be controversial ... see also:  bids-standard/legacy-validator#599
- [x] ~Discuss, whether the `name` column in `electrodes.tsv` and `channels.tsv` HAS to correspond and if yes, how to check it~ according to our definitions, they do not correspond... e.g., there can be two electrodes forming a single channel.
- [x] remove support for Neuroscan CNT
- [ ] think about introducing a check that parses the `channels.tsv` file and counts the number of EEG, EOG, EMG, etc. channels ... then compares this count that is given in the `*_eeg.json` ... check for validity - raise error if no assertion ... see bids-standard/bids-validator#80
- [x] solve bids-standard/legacy-validator#601 
- [ ] solve bids-standard/bids-validator#81 
- [x] solve bids-standard/legacy-validator#477 
- [ ] incorporate a check: if `electrodes.tsv` is included, there MUST be a `coordsystem.json` included as well. see bids-standard/legacy-validator#672 
- ~think about a better way to check for required columns in `channels.tsv` an `electrodes.tsv`. Currently done by asserting order of column names: But the order should be irrelevant, as long as all columns are present.~ this is fine ... leave it as is: It increases consistency across datasets and is not a lot of effort during data preparation
- [ ] finally: remove bep006 flag (i.e., from now on it is always "true")

**Comment by sappelhoff** [comment]
@chrisfilo can we get an EEG tag, please?

**Comment by sappelhoff** [comment]
In my opinion, the outstanding three tick boxes (see OP) and bids-standard/bids-validator#81 refer to enhancements that are not blocking a merge of the BEP006 validator into the master validator.

If it is okay with everyone, I would open three separate issues to track these enhancements individually.

Then the final tick mark would be removing the `bep006` flag from the validator, to make the EEG modality part of the master. I am not sure, whether this should happen **before**, **after**, or **simultaneously** to merging the text of BEP006 into the `bids-specification`.

Opinions on this ?

**Comment by chrisgorgo** [comment]
+1 for splitting into multiple issues

I think it would be most sensible to remove the `bep006` flag after the BEP is merged since it guarantees nothing will change in the spec.

**Comment by sappelhoff** [comment]
Alright, I split this up into single issues and tagged them appropriately.

closing this issue in favor of a more thorough roadmap, see: https://github.com/bids-standard/bids-specification/issues/107
